FROM redis

WORKDIR /etc/redis

COPY ./replica-sentinel/redis.conf .
COPY ./replica-sentinel/script.sh .
COPY ./replica-sentinel/sentinel.conf .
COPY ./replica-sentinel/sentinel-users.acl .
COPY ./users.acl .
